import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import dashboardRouter from "./dashboard";
import clientsRouter from "./clients";
import projectsRouter from "./projects";
import stagesRouter from "./stages";
import feedbackRouter from "./feedback";
import estimatesRouter from "./estimates";
import plansRouter from "./plans";
import officesRouter from "./offices";
import clientPortalRouter from "./client-portal";
import filesRouter from "./files";
import boqRouter from "./boq";
import subscriptionRouter from "./subscription";
import onboardingRouter from "./onboarding";
import documentsRouter from "./documents";
import notificationsRouter from "./notifications";
import tasksRouter from "./tasks";
import invoicesRouter from "./invoices";
import reportsRouter from "./reports";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(clientPortalRouter);
router.use(filesRouter);
router.use(dashboardRouter);
router.use(clientsRouter);
router.use(projectsRouter);
router.use(stagesRouter);
router.use(feedbackRouter);
router.use(estimatesRouter);
router.use(plansRouter);
router.use(officesRouter);
router.use(boqRouter);
router.use(subscriptionRouter);
router.use(onboardingRouter);
router.use(documentsRouter);
router.use(notificationsRouter);
router.use(tasksRouter);
router.use(invoicesRouter);
router.use(reportsRouter);

export default router;
