export const AR = {
  loadingProjectData: "تعذّر تحميل بيانات المشروع",
  chooseFile: "يرجى اختيار ملف",
  pleaseWriteRevisionNote: "يرجى كتابة ملاحظة التعديل",
  stageApprovedSuccessfully: "تمت الموافقة على المرحلة بنجاح",
  revisionRequestSent: "تم إرسال طلب التعديل بنجاح",
  fileUploadedSuccessfully: "تم رفع الملف بنجاح",
  fileDeleted: "تم حذف الملف",
  approvedVersionSet: "تم تعيين النسخة المعتمدة",
  projectFiles: "ملفات المشروع",
  uploadFile: "رفع ملف",
  relatedStage: "المرحلة المرتبطة",
  category: "التصنيف",
  notes: "الملاحظات",
  version: "نسخة",
  internalOnly: "داخلي فقط",
  clientVisible: "ظاهر للعميل",
  approvedVersion: "النسخة المعتمدة",
  setApprovedVersion: "تعيين كنسخة معتمدة",
  download: "تحميل",
  delete: "حذف",
  noProjectFiles: "لا توجد ملفات مشتركة بعد",
  noAdminProjectFiles: "لا توجد ملفات مرفوعة بعد",
  noStages: "لا توجد مراحل مسجلة بعد",
  noNotes: "لا توجد ملاحظات مسجلة",
  genericError: "حدث خطأ",
};
